// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFxCD9wG2qbEYvBRjasSszBe2ML8XVhMw',
    appId: '1:890326043621:web:b8b7d965d590889244bd0c',
    messagingSenderId: '890326043621',
    projectId: 'contacts-app-c35e3',
    authDomain: 'contacts-app-c35e3.firebaseapp.com',
    storageBucket: 'contacts-app-c35e3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDh2ViPw4fMmyXUJvs7v791c5QhBFza8i4',
    appId: '1:890326043621:android:3c0efc0528ec428044bd0c',
    messagingSenderId: '890326043621',
    projectId: 'contacts-app-c35e3',
    storageBucket: 'contacts-app-c35e3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDapTFZkbWHa7cURSrpt3qAk-R04hRtzzQ',
    appId: '1:890326043621:ios:5205b4f411c9251944bd0c',
    messagingSenderId: '890326043621',
    projectId: 'contacts-app-c35e3',
    storageBucket: 'contacts-app-c35e3.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceAdminApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDapTFZkbWHa7cURSrpt3qAk-R04hRtzzQ',
    appId: '1:890326043621:ios:5205b4f411c9251944bd0c',
    messagingSenderId: '890326043621',
    projectId: 'contacts-app-c35e3',
    storageBucket: 'contacts-app-c35e3.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceAdminApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFxCD9wG2qbEYvBRjasSszBe2ML8XVhMw',
    appId: '1:890326043621:web:104a70782fa3625944bd0c',
    messagingSenderId: '890326043621',
    projectId: 'contacts-app-c35e3',
    authDomain: 'contacts-app-c35e3.firebaseapp.com',
    storageBucket: 'contacts-app-c35e3.firebasestorage.app',
  );
}
